import { ApiError, handleApiError, jsonOk, parseJson } from '@/lib/server/api';
import { writeAuditLog } from '@/lib/server/audit';
import { requireWorkspace } from '@/lib/server/auth';
import { createId, mutateDb, now, readDb } from '@/lib/server/db';
import { generateRfqEmailDraft } from '@/lib/server/rfq-email';
import { rfqSchema } from '@/lib/server/validation';
import type { Rfq, RfqItem } from '@/lib/server/schema';

export async function GET(_: Request, { params }: { params: Promise<{ rfqId: string }> }) { try { const { workspace } = await requireWorkspace(); const { rfqId } = await params; const db = await readDb(); const rfq = db.rfqs.find((item) => item.id === rfqId && item.workspaceId === workspace.id); if (!rfq) throw new ApiError(404, 'RFQ_NOT_FOUND', 'RFQ was not found.'); return jsonOk({ rfq, items: db.rfqItems.filter((item) => item.rfqId === rfq.id && item.workspaceId === workspace.id), suppliers: db.suppliers.filter((supplier) => rfq.supplierIds.includes(supplier.id) && supplier.workspaceId === workspace.id), auditLogs: db.auditLogs.filter((log) => log.workspaceId === workspace.id && log.entityId === rfq.id) }); } catch (error) { return handleApiError(error); } }
export async function PUT(request: Request, { params }: { params: Promise<{ rfqId: string }> }) { try { const { user, workspace } = await requireWorkspace(['owner', 'admin', 'member']); const { rfqId } = await params; const input = await parseJson(request, rfqSchema); const result = await mutateDb((db) => { const rfq = db.rfqs.find((item) => item.id === rfqId && item.workspaceId === workspace.id); if (!rfq) throw new ApiError(404, 'RFQ_NOT_FOUND', 'RFQ was not found.'); const supplierIds = input.supplierIds.filter((id: string) => db.suppliers.some((supplier) => supplier.id === id && supplier.workspaceId === workspace.id && !supplier.archivedAt)); if (supplierIds.length !== input.supplierIds.length) throw new ApiError(400, 'INVALID_SUPPLIERS', 'One or more suppliers are not available in this workspace.'); Object.assign(rfq, { title: input.title, description: input.description || undefined, neededBy: input.neededBy || undefined, deliveryLocation: input.deliveryLocation || undefined, internalReference: input.internalReference || undefined, supplierIds, updatedAt: now() }); db.rfqItems = db.rfqItems.filter((item) => !(item.rfqId === rfq.id && item.workspaceId === workspace.id)); const items: RfqItem[] = input.items.map((item: any) => ({ id: createId('rfi'), workspaceId: workspace.id, rfqId: rfq.id, itemName: item.itemName, description: item.description || undefined, quantity: item.quantity, unit: item.unit || undefined, requiredDate: item.requiredDate || undefined, notes: item.notes || undefined, createdAt: now() })); db.rfqItems.push(...items); const suppliers = db.suppliers.filter((supplier) => supplierIds.includes(supplier.id)); rfq.emailDraft = generateRfqEmailDraft({ rfq, items, suppliers, workspaceName: workspace.name }); return { rfq, items }; }); await writeAuditLog({ workspaceId: workspace.id, actorUserId: user.id, action: 'rfq.updated', entityType: 'rfq', entityId: result.rfq.id }); return jsonOk(result); } catch (error) { return handleApiError(error); } }
