ALTER TABLE quote_documents ADD COLUMN source_text TEXT;
ALTER TABLE ai_extraction_runs ADD COLUMN raw_ai_response TEXT;
ALTER TABLE supplier_quotes ADD COLUMN quote_document_id TEXT REFERENCES quote_documents(id) ON DELETE SET NULL;
ALTER TABLE supplier_quotes ADD COLUMN extracted_fields JSONB;
ALTER TABLE supplier_quotes ADD COLUMN reviewed_fields JSONB;
ALTER TABLE supplier_quotes ADD COLUMN extraction_status TEXT NOT NULL DEFAULT 'needs_review' CHECK (extraction_status IN ('pending','processing','needs_review','approved','failed'));
ALTER TABLE supplier_quotes ADD COLUMN quote_reference TEXT;
ALTER TABLE supplier_quotes ADD COLUMN quote_date DATE;
ALTER TABLE supplier_quotes ADD COLUMN valid_until DATE;
ALTER TABLE supplier_quotes ADD COLUMN payment_terms TEXT;
ALTER TABLE supplier_quotes ADD COLUMN freight_terms TEXT;
ALTER TABLE supplier_quotes ADD COLUMN estimated_lead_time TEXT;
ALTER TABLE supplier_quotes ADD COLUMN delivery_date DATE;
ALTER TABLE supplier_quotes ADD COLUMN taxes NUMERIC(14, 4);
ALTER TABLE supplier_quotes ADD COLUMN total_price NUMERIC(14, 4);
ALTER TABLE supplier_quotes ADD COLUMN notes TEXT;
ALTER TABLE quote_line_items ADD COLUMN item_name TEXT;
ALTER TABLE quote_line_items ADD COLUMN unit TEXT;
ALTER TABLE quote_line_items ADD COLUMN extended_price NUMERIC(14, 4);
ALTER TABLE quote_line_items ADD COLUMN alternatives TEXT;
ALTER TABLE quote_line_items ADD COLUMN notes TEXT;
