'use client';
import { FormEvent, useState } from 'react';
const fieldNames = ['supplierName','quoteReference','quoteDate','validUntil','currency','paymentTerms','freightTerms','estimatedLeadTime','deliveryDate','taxes','totalPrice','notes'];
function badge(confidence?: number) { const score = Number(confidence ?? 0); return <span className={score < 60 ? 'confidence low' : 'confidence'}>{score < 60 ? 'Needs Review' : `${score}%`}</span>; }
export function QuoteReviewForm({ rfqId, quote }: { rfqId: string; quote: any }) {
  const [fields, setFields] = useState(quote.reviewedFields ?? quote.extractedFields ?? { lineItems: [] }); const [error, setError] = useState(quote.extractionStatus === 'failed' ? 'Extraction failed. You can manually enter fields, save a draft, or re-run extraction.' : '');
  function update(name: string, value: string) { setFields({ ...fields, [name]: { ...(fields[name] ?? { confidence: 35 }), value } }); }
  function updateLine(index: number, name: string, value: string) { const lineItems = [...(fields.lineItems ?? [])]; lineItems[index] = { ...lineItems[index], [name]: { ...(lineItems[index]?.[name] ?? { confidence: 35 }), value } }; setFields({ ...fields, lineItems }); }
  async function save(approve: boolean) { const response = await fetch(`/api/rfqs/${rfqId}/quotes/${quote.id}/review`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ fields, approve }) }); const result = await response.json(); if (!result.ok) { setError(result.error?.message ?? 'Could not save review.'); return; } window.location.href = `/app/rfqs/${rfqId}`; }
  async function rerun() { setError('Re-running extraction...'); const response = await fetch(`/api/rfqs/${rfqId}/quotes/${quote.id}/rerun`, { method: 'POST' }); if (!response.ok) { const result = await response.json().catch(() => null); setError(result?.error?.message ?? 'Extraction could not be re-run. You can continue with manual entry.'); return; } window.location.reload(); }
  return <form className="review-fields" onSubmit={(event: FormEvent) => { event.preventDefault(); void save(false); }}>{fieldNames.map((name) => <label key={name}>{name.replace(/([A-Z])/g, ' $1')} {badge(fields?.[name]?.confidence)}<input value={fields?.[name]?.value ?? ''} onChange={(event) => update(name, event.target.value)} /></label>)}<h2>Line items</h2>{(fields.lineItems ?? []).map((line: any, index: number) => <div className="line-item-card" key={index}>{['itemName','description','quantity','unit','unitPrice','extendedPrice','leadTime','alternatives','notes'].map((name) => <label key={name}>{name.replace(/([A-Z])/g, ' $1')} {badge(line?.[name]?.confidence)}<input value={line?.[name]?.value ?? ''} onChange={(event) => updateLine(index, name, event.target.value)} /></label>)}</div>)}{error && <p className="form-error" role="alert">{error}</p>}<div className="form-actions"><button className="button secondary" type="submit">Save draft</button><button className="button primary" type="button" onClick={() => save(true)}>Approve quote</button><button className="button secondary" type="button" onClick={rerun}>Re-run extraction</button></div></form>;
}
