import { ApiError, handleApiError, jsonOk, parseJson } from '@/lib/server/api';
import { writeAuditLog } from '@/lib/server/audit';
import { requireWorkspace } from '@/lib/server/auth';
import { mutateDb, now, readDb } from '@/lib/server/db';
import { supplierSchema } from '@/lib/server/validation';

export async function GET(_: Request, { params }: { params: Promise<{ supplierId: string }> }) { try { const { workspace } = await requireWorkspace(); const { supplierId } = await params; const db = await readDb(); const supplier = db.suppliers.find((item) => item.id === supplierId && item.workspaceId === workspace.id && !item.archivedAt); if (!supplier) throw new ApiError(404, 'SUPPLIER_NOT_FOUND', 'Supplier was not found.'); return jsonOk({ supplier }); } catch (error) { return handleApiError(error); } }
export async function PUT(request: Request, { params }: { params: Promise<{ supplierId: string }> }) { try { const { user, workspace } = await requireWorkspace(['owner', 'admin', 'member']); const { supplierId } = await params; const input = await parseJson(request, supplierSchema); const supplier = await mutateDb((db) => { const supplier = db.suppliers.find((item) => item.id === supplierId && item.workspaceId === workspace.id && !item.archivedAt); if (!supplier) throw new ApiError(404, 'SUPPLIER_NOT_FOUND', 'Supplier was not found.'); Object.assign(supplier, { ...input, contactPerson: input.contactPerson || undefined, email: input.email || undefined, phone: input.phone || undefined, website: input.website || undefined, category: input.category || undefined, typicalItems: input.typicalItems || undefined, paymentTerms: input.paymentTerms || undefined, notes: input.notes || undefined, updatedAt: now() }); return supplier; }); await writeAuditLog({ workspaceId: workspace.id, actorUserId: user.id, action: 'supplier.updated', entityType: 'supplier', entityId: supplier.id }); return jsonOk({ supplier }); } catch (error) { return handleApiError(error); } }
export async function DELETE(_: Request, { params }: { params: Promise<{ supplierId: string }> }) { try { const { user, workspace } = await requireWorkspace(['owner', 'admin']); const { supplierId } = await params; const supplier = await mutateDb((db) => { const supplier = db.suppliers.find((item) => item.id === supplierId && item.workspaceId === workspace.id && !item.archivedAt); if (!supplier) throw new ApiError(404, 'SUPPLIER_NOT_FOUND', 'Supplier was not found.'); supplier.status = 'inactive'; supplier.archivedAt = now(); supplier.updatedAt = now(); return supplier; }); await writeAuditLog({ workspaceId: workspace.id, actorUserId: user.id, action: 'supplier.updated', entityType: 'supplier', entityId: supplier.id, metadata: { archived: true } }); return jsonOk({ supplier }); } catch (error) { return handleApiError(error); } }
