import Link from 'next/link';
import { requirePageWorkspace } from '@/lib/server/auth';
import { readDb } from '@/lib/server/db';

export const metadata = { title: 'Dashboard | ProcureIQ', description: 'ProcureIQ workspace dashboard.' };
export default async function DashboardPage() { const { user, workspace, membership } = await requirePageWorkspace(); const db = await readDb(); const scopedRfqs = db.rfqs.filter((item) => item.workspaceId === workspace.id); const scopedQuotes = db.supplierQuotes.filter((item) => item.workspaceId === workspace.id); const cards = [['Active RFQs', scopedRfqs.filter((rfq) => rfq.status !== 'archived').length], ['Quotes received', scopedQuotes.length], ['Pending review', scopedQuotes.filter((quote) => quote.status === 'needs_review').length], ['PO drafts', db.purchaseOrderDrafts.filter((item) => item.workspaceId === workspace.id).length], ['Supplier response rate', '—'], ['Estimated time saved', '—']]; return <main><section className="app-shell"><div className="app-top"><div><p className="eyebrow">Workspace dashboard</p><h1>{workspace.name}</h1><p>Welcome back, {user.name}. Your role is {membership.role}.</p></div><Link className="button primary" href="/app/rfqs/new">Create RFQ</Link></div><div className="dashboard-grid">{cards.map(([label, value]) => <article key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="workflow-visual" aria-label="RFQ workflow"><span>RFQ</span><i /> <span>Quotes</span><i /> <span>Compare</span><i /> <span>Approve</span><i /> <span>PO</span></section><section className="workspace-panel"><h2>Procurement workflow foundation</h2><p>Create suppliers, prepare RFQs, generate supplier-ready email drafts, and keep every request scoped to {workspace.name}.</p></section></section></main>; }
<<<<<<< HEAD
=======
export default async function DashboardPage() { const { user, workspace, membership } = await requirePageWorkspace(); const db = await readDb(); const scoped = { suppliers: db.suppliers.filter((item) => item.workspaceId === workspace.id).length, rfqs: db.rfqs.filter((item) => item.workspaceId === workspace.id).length, quoteDocuments: db.quoteDocuments.filter((item) => item.workspaceId === workspace.id).length, poDrafts: db.purchaseOrderDrafts.filter((item) => item.workspaceId === workspace.id).length }; return <main><section className="app-shell"><div className="app-top"><div><p className="eyebrow">Workspace dashboard</p><h1>{workspace.name}</h1><p>Welcome back, {user.name}. Your role is {membership.role}.</p></div><Link className="button secondary" href="/app/settings/company">Company settings</Link></div><div className="dashboard-grid">{Object.entries(scoped).map(([label, value]) => <article key={label}><strong>{value}</strong><span>{label.replace(/([A-Z])/g, ' $1')}</span></article>)}</div><section className="workspace-panel"><h2>Backend foundation active</h2><p>Every protected view reads the signed session server-side and scopes workspace data before rendering. RFQs, suppliers, quote documents, supplier quotes, line items, purchase order drafts, AI extraction runs, and audit logs are modeled for the procurement workflow.</p></section></section></main>; }
>>>>>>> origin/main
