import { ApiError, handleApiError, jsonOk, parseJson } from '@/lib/server/api';
import { writeAuditLog } from '@/lib/server/audit';
import { requireWorkspace } from '@/lib/server/auth';
import { createId, mutateDb, now, readDb } from '@/lib/server/db';
import { generateRfqEmailDraft } from '@/lib/server/rfq-email';
import { rfqSchema } from '@/lib/server/validation';
import type { Rfq, RfqItem } from '@/lib/server/schema';

export async function GET() { try { const { workspace } = await requireWorkspace(); const db = await readDb({ workspaceId: workspace.id }); return jsonOk({ rfqs: db.rfqs.filter((item) => item.workspaceId === workspace.id) }); } catch (error) { return handleApiError(error); } }
export async function POST(request: Request) { try { const { user, workspace } = await requireWorkspace(['owner', 'admin', 'member']); const input = await parseJson(request, rfqSchema); const result = await mutateDb((db) => { const supplierIds = input.supplierIds.filter((id: string) => db.suppliers.some((supplier) => supplier.id === id && supplier.workspaceId === workspace.id && !supplier.archivedAt)); if (supplierIds.length !== input.supplierIds.length) throw new ApiError(400, 'INVALID_SUPPLIERS', 'One or more suppliers are not available in this workspace.'); const timestamp = now(); const rfq: Rfq = { id: createId('rfq'), workspaceId: workspace.id, createdByUserId: user.id, title: input.title, description: input.description || undefined, neededBy: input.neededBy || undefined, deliveryLocation: input.deliveryLocation || undefined, internalReference: input.internalReference || undefined, supplierIds, status: 'draft' as const, createdAt: timestamp, updatedAt: timestamp }; const items: RfqItem[] = input.items.map((item: any) => ({ id: createId('rfi'), workspaceId: workspace.id, rfqId: rfq.id, itemName: item.itemName, description: item.description || undefined, quantity: item.quantity, unit: item.unit || undefined, requiredDate: item.requiredDate || undefined, notes: item.notes || undefined, createdAt: timestamp })); const suppliers = db.suppliers.filter((supplier) => supplierIds.includes(supplier.id)); rfq.emailDraft = generateRfqEmailDraft({ rfq, items, suppliers, workspaceName: workspace.name }); db.rfqs.push(rfq); db.rfqItems.push(...items); const w = db.workspaces.find((item) => item.id === workspace.id) as any; if (w) w.usage = { rfqsCreated: (w.usage?.rfqsCreated ?? 0) + 1, quoteDocumentsUploaded: w.usage?.quoteDocumentsUploaded ?? 0, aiExtractionRuns: w.usage?.aiExtractionRuns ?? 0, teamMembers: db.workspaceMembers.filter((member) => member.workspaceId === workspace.id).length }; return { rfq, items }; }, { workspaceId: workspace.id }); await writeAuditLog({ workspaceId: workspace.id, actorUserId: user.id, action: 'rfq.created', entityType: 'rfq', entityId: result.rfq.id }); return jsonOk(result, { status: 201 }); } catch (error) { return handleApiError(error); } }
